# Edit the below catalog file template and click save to import a test version of it on Roadie
apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: linking-test-component
  description: |
    component for testing catalog internal linkins
spec:
  # Spec type is always hardcoded to preview-entity in preview mode
  type: website
  owner: group:roadiehq/sample-team
  lifecycle: experimental

